### ISSUE TITLE
Cache healthz responses for 60 seconds

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium-java#275] opened 2020-06-21 18:43 UTC
## Description

- In order to prevent a DoS attack on the /healthz and /healthz/ietf endpoints, cache the response for 60 (config) seconds
- checking the headers from curl or http, there isn't a cache-control header

## Expected Behavior

- response is cached
- cache control header set

## Reproduce

- use httpie or curl to check the response headers

**Comment by jofultz** [comment] 2020-06-24 15:49
I've implemented caching in [jofultz-cache](https://github.com/retaildevcrews/helium-java/tree/jofultz-cache).  However, @Cacheable doesn't work properly with WebFlux (reactor core).  The issue is that it caches the Mono/Flux object and not the rendered result.  In the case of the ietf endpoint this means that each time it fetches the same object instance and the subscribes to it.  This results in multiple issues:

- the duration calculation is off for the first fetch (genres) in a chain of calls
- all calls are still performed to the back-end system and thus caching is ineffective
- the behaviour of caching and reusing the publisher object long-term is unknown

There is a caching [add-on](https://github.com/reactor/reactor-addons/tree/master/reactor-extra/src/main/java/reactor/cache), but it requires the actual service code to incorporate the cache code (e.g., cache-aside pattern) and the means to manage the cache expiry would be implemented as an externalized function.

I suggest we skip this requirement for the Java version and close the item with reference to these comments.

**Comment by jofultz** [comment] 2020-06-25 15:10
Closing per previous comments.

**Closed by jofultz** 2020-06-25 15:10 UTC
Labels: Bug, Java, Pri1
